### ISSUE TITLE
Attempting to create a new Quantum Register inside a custom gate definition crashes the server

### ISSUE THREAD

**Issue by DRovara** [cda-tum/mqt-ddvis#281]
**Description:**

Trying to create a new register (`qreg` or `creg`) inside a custom gate definition causes the entire server to crash. It seems that the server's background process gets stuck in some very resource-intensive loop (eventually, it caused my entire system to crash), as the terminal displays no further logs and even trying to connect again through a new browser window or reloading the page doesn't work.

**Expected Behavior:**

While creating new registers inside a custom gate definition is not supported, it should not be enough to cause the server to crash. Instead, some error message should be displayed.

**How to Reproduce:**

The following minimal OpenQASM code example is enough to make the process crash:

```
qreg q[1];

gate test a {
  qreg crash[2];
  x a;
}

test q[0];
```

It will also crash if I create a `creg` instead.

**Comment by burgholzer** [comment]
Thanks for catching this! I fully agree that this should not be causing a server crash!
I would suspect that this is an issue with not catching an exception being thrown from the QASM parser in mqt-core.

I'll take a look!

**Comment by burgholzer** [comment]
This is being fixed in https://github.com/cda-tum/mqt-core/pull/700

**Comment by burgholzer** [comment]
This is now live at https://www.cda.cit.tum.de/app/ddvis/ 🚀
